server:
  port: 8081
  servlet:
    context-path: /
    multipart:
      max-file-size: 200000000
      max-request-size: 200000000
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    relaxedPathChars: '<,>,[,\,],^,`,{,|,}'
    relaxedQueryChars: '<,>,[,\,],^,`,{,|,}'
    uri-encoding: UTF-8

spring:
  datasource:
    dbcp2:
      min-idle: 3
      max-idle: 20
      max-wait-millis: 5000
      validation-query: select 1
      initial-size: 1
      max-total: 20
      max-active: 3
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      test-on-borrow: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6789/wk?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    url: jdbc:mysql://103.241.72.78:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wk202311
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  redis:
    host: 127.0.0.1
    port: 6379